app/accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'

urlpatterns =[
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
]

app/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
	path('purchase', views.purchase, name='purchase'),
	path('add/<int:item_id>', views.add, name='add'),
	path('remove', views.remove, name='remove'),
	path('', views.cart, name='cart')
]

app/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
	path('bought_log', views.bought_log, name='bought_log'),
	path('post', views.item_post, name='item_post'),
	path('<int:item_id>', views.detail, name='item_detail'),
	path('', views.index, name='index'),
]

app/simple_ec/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
		path('cart/', include('cart.urls')),
		path('accounts/', include('accounts.urls')),
		path('', include('home.urls')),
]

app/accounts/models.py
from django.db import models

# Create your models here.

app/cart/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from home.models import Item

class Cart(models.Model):
		cart_id = models.ForeignKey(User, verbose_name=_("cart_id"), on_delete=models.CASCADE)
		items = models.ManyToManyField(Item, related_name="items", blank=True, through='Cart_Item')
		created_at = models.DateTimeField(auto_now_add=True)
		updated_at = models.DateTimeField(auto_now=True)

		def __str__(self):
				return self.cart_id

class Cart_Item(models.Model):
		cart = models.ForeignKey(Cart, verbose_name=_("cart"), on_delete=models.CASCADE)
		item = models.ForeignKey(Item, verbose_name=_("item"), on_delete=models.CASCADE)
		quantity = models.IntegerField(verbose_name=_("quantity"), default=0)
		created_at = models.DateTimeField(auto_now_add=True)

		class Meta:
				unique_together = ('cart', 'item')

		def __str__(self):
				return self.item.name

class Bought_Log(models.Model):
		user = models.ForeignKey(User, verbose_name=_("user"), on_delete=models.CASCADE)
		item = models.ForeignKey(Item, verbose_name=_("item"), on_delete=models.CASCADE)
		quantity = models.IntegerField(verbose_name=_("quantity"), default=0)
		created_at = models.DateTimeField(auto_now_add=True)

		def __str__(self):
				return self.user.username + " bought " + str(self.quantity) + " " + self.item.name + "(s)" + " at " + self.created_at.strftime("%Y-%m-%d %H:%M:%S") + "\n\t" + "total price: $" + str(self.item.price * self.quantity)

app/home/models.py
from django.db import models

class Item(models.Model):
		name = models.CharField(max_length=50, unique=True)
		description = models.CharField(max_length=200, blank=True, default="")
		price = models.IntegerField(blank=False, null=False)
		stock = models.IntegerField(blank=False, null=False)

		def __str__(self):
				return self.name

app/accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in self.fields.values():
			field.widget.attrs['class'] = 'form-control'
			field.widget.attrs['placeholder'] = field.label

app/accounts/views.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(LoginView, LogoutView)
from .forms import LoginForm


class Login(LoginView):
    form_class = LoginForm
    template_name = 'login.html'

class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'login.html'

app/cart/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render

from home.models import Item
from cart.models import Cart, Cart_Item, Bought_Log
from django.contrib.auth.models import User

def cart(request):
		user = request.user
		if not user.is_authenticated:
			return HttpResponseRedirect(reverse('accounts:login'))
		try:
			cart = Cart.objects.get(cart_id=user)
		except Cart.DoesNotExist:
			cart = Cart.objects.create(cart_id=user)
		items = cart.cart_item_set.all()
		total_price = 0
		for item in items:
			total_price += item.item.price * item.quantity
		return render(request, 'cart.html', {'items': items, 'total_price': total_price})

def add(request, item_id):
	user = request.user
	if not user.is_authenticated:
		return HttpResponseRedirect(reverse('accounts:login'))
	if not request.method == 'POST':
		return HttpResponse("Invalid request")
	quantity = int(request.POST['quantity'])
	if quantity <= 0:
		return HttpResponse("Invalid quantity")
	try:
		item = Item.objects.get(id=item_id)
	except Item.DoesNotExist:
		return HttpResponse("Item not found")
	try:
		cart = Cart.objects.get(cart_id=user)
	except Cart.DoesNotExist:
		cart = Cart.objects.create(cart_id=user)
	try:
		cart_item = Cart_Item.objects.get(cart=cart, item=item)
		cart_item.quantity += quantity
		cart_item.save()
	except Cart_Item.DoesNotExist:
		cart_item = Cart_Item.objects.create(cart=cart, item=item, quantity=quantity)
	cart.items.add(item, through_defaults={'quantity': cart_item.quantity})
	cart.save()
	return HttpResponseRedirect(reverse('cart:cart'))

def remove(request):
	user = request.user
	if not user.is_authenticated:
		return HttpResponseRedirect(reverse('accounts:login'))
	if not request.method == 'POST':
		return HttpResponse("Invalid request")
	cart_item_id = request.POST['cart_item_id']
	try:
		cart = Cart.objects.get(cart_id=user)
	except Cart.DoesNotExist:
		cart = Cart.objects.create(cart_id=user)
		return HttpResponse("Cart is empty")
	try:
		Cart_Item.objects.get(id=cart_item_id).delete()
		cart.save()
	except Cart_Item.DoesNotExist:
		return HttpResponse("Item not found")
	cart.save()
	return HttpResponseRedirect(reverse('cart:cart'))

def purchase(request):
	user = request.user
	if not user.is_authenticated:
		return HttpResponseRedirect(reverse('accounts:login'))
	if not request.method == 'POST':
		return HttpResponse("Invalid request")
	try:
		cart = Cart.objects.get(cart_id=user)
	except Cart.DoesNotExist:
		cart = Cart.objects.create(cart_id=user)
		return HttpResponse("Cart is empty")
	items = cart.cart_item_set.all()
	for item in items:
		if item.quantity > item.item.stock:
			return HttpResponse("Item out of stock")
	for item in items:
		Bought_Log.objects.create(user=user, item=item.item, quantity=item.quantity)
		item.item.stock -= item.quantity
		item.item.save()
		item.delete()
	cart.save()
	return HttpResponseRedirect(reverse('home:index'))

app/home/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from .models import Item
from cart.models import Bought_Log
from django.contrib.auth.models import User

def index(request):
		items = Item.objects.filter(stock__gte=1)
		return render(request, 'home.html', {'items': items})

def detail(request, item_id):
		try:
			item = Item.objects.get(id=item_id)
			return render(request, 'item_detail.html', {'item': item})
		except Item.DoesNotExist:
			return HttpResponse("Item not found")

def item_post(request):
	if request.method == 'GET':
		return render(request, 'item_post.html')
	elif request.method == 'POST':
		name = request.POST['name']
		description = request.POST['description']
		price = int(request.POST['price'])
		quantity = int(request.POST['quantity'])
		if not name or not price or not quantity:
			return HttpResponse("Invalid input")
		item, created = Item.objects.get_or_create(name=name, defaults={'description': description, 'price': price, 'stock': quantity})
		if created:
			return HttpResponseRedirect(reverse('home:index'))
		else:
			if description:
				item.description = description
			item.price = price
			item.stock += quantity
			item.save()
			return HttpResponseRedirect(reverse('home:item_detail', args=(item.id,)))

def bought_log(request):
	user = request.user
	if not user.is_authenticated:
		return HttpResponseRedirect(reverse('accounts:login'))
	if not user.is_superuser:
		return HttpResponse("Permission denied")
	bought_logs = Bought_Log.objects.all()
	return render(request, 'bought_log.html', {'bought_logs': bought_logs})

app/accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
	{% csrf_token %}
	{% for field in form %}
		<div class="form-group has-feedback">
			{{ field }}
		</div>
	{% endfor %}
	<div class="row">

		{% for error in form.non_field_errors %}
			<div class="alert alert-danger" role="alert">
				<p>{{ error }}</p>
			</div>
		{% endfor %}
		<button type="submit" class="btn btn-primary btn-block btn-flat">ログオン</button>
	</div>
</form>
{% endblock %}

app/cart/templates/cart.html
{% extends 'base.html' %}

{% load mathfilters %}
{% block content %}
		<h3>{{ user.get_username }}'s cart</h3>
		{% for item in items %}
		<div>
			<p style="display: inline-block;">{{ item.item.name }} - {{ item.quantity }} ${{ item.quantity|mul:item.item.price }}</p>
			<form method='POST' action="{% url 'cart:remove' %}" style="display: inline-block;">
				{% csrf_token %}
				<input type="hidden" name="cart_item_id" value={{ item.id }}>
				<button type="submit">remove from cart</button>
			</form>
		</div>
		{% endfor %}
		<p>Total: ${{ total_price }}</p>
		<form method='POST' action="{% url 'cart:purchase' %}">
			{% csrf_token %}
			<button type="submit">purchase</button>
		</form>
{% endblock %}

app/home/templates/bought_log.html
{% extends 'base.html' %}

{% block content %}
<h1>Log</h1>
		<ul>
		{% for log in bought_logs %}
			<li>{{ log }}</li>
		{% endfor %}
		</ul>
{% endblock %}

app/home/templates/home.html
{% extends 'base.html' %}

{% block content %}
	<h3>Items</h3>
	<ul>
	{% for item in items %}
			<li>
				<a href="{% url 'home:item_detail' item.id %}"> {{ item.name }} </a>
			</li>
			<br>
	{% endfor %}
	</ul>
{% endblock %}

app/home/templates/item_detail.html
{% extends 'base.html' %}

{% block content %}
	<h4>Name</h4>
	<p>{{ item.name }}</p>
	<h4>Description<h4>
	<p>{{ item.description }}</p>
	<h4>Price</h4>
	<p>{{ item.price }}</p>
	<h4>Stock</h4>
	<p>{{ item.stock }}</p>
	<form method="POST" action="{% url 'cart:add' item.id %}">
		{% csrf_token %}
		<input type="number" name="quantity" placeholder="quantity"><br>
		<button type="submit">Add to cart</button>
	</form>
	<a href="{% url 'home:index' %}"> return home </a>
{% endblock %}

app/home/templates/item_post.html
{% extends 'base.html' %}

{% block content %}
	<form method="POST" action="{% url 'home:item_post' %}">
		{% csrf_token %}
		<input type="text" name="name" placeholder="name"><br>
		<textarea name="description" placeholder="description"></textarea><br>
		<input type="number" name="price" placeholder="price"><br>
		<input type="number" name="quantity" placeholder="quantity"><br>
		<button type="submit">Submit</button>
	</form>
{% endblock %}

app/simple_ec/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Simple EC</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <header>
        <h1>Simple EC</h1>
        <nav>
            <ul>
								<li><a href="{% url 'home:item_post' %}">Add Item</a></li>
								{% if user.is_authenticated %}
								<li><a>User: {{ user.get_username }}</a></li>
								<li><a href="{% url 'accounts:logout' %}">Logout</a></li>
								<li><a href="{% url 'cart:cart' %}">Cart</a></li>
								{% else %}
								<li><a href="{% url 'accounts:login' %}">Login</a></li>
								{% endif %}
            </ul>
        </nav>
    </header>
		<hr>
    <main>
        {% block content %}
        {% endblock %}
    </main>
		<hr>
    <footer>
				<p>Simple EC</p>
				<ul>
					<li><a href="{% url 'home:index' %}">Home</a></li>
					<li><a href="{% url 'home:bought_log' %}">Bought Log</a></li>
				</ul>
    </footer>
</body>
</html>